import { Node, Edge } from 'reactflow';

export const flowToPython = (nodes: Node[], edges: Edge[], agentName: string) => {
    const imports = [
        'from botchain import Agent, Node, Edge',
        'import os'
    ];

    let script = `"""\nAgent: ${agentName}\nGenerated by BotChain\n"""\n\n`;
    script += imports.join('\n') + '\n\n';

    script += `def run_agent(inputs={}):\n`;
    script += `    # Agent Configuration\n`;
    script += `    agent_config = {\n`;
    script += `        "name": "${agentName}",\n`;
    script += `        "nodes": [\n`;

    nodes.forEach(node => {
        script += `            {\n`;
        script += `                "id": "${node.id}",\n`;
        script += `                "type": "${node.type}",\n`;
        script += `                "data": ${JSON.stringify(node.data, null, 4).replace(/\n/g, '\n                ')}\n`;
        script += `            },\n`;
    });

    script += `        ],\n`;
    script += `        "edges": [\n`;

    edges.forEach(edge => {
        script += `            { "source": "${edge.source}", "target": "${edge.target}" },\n`;
    });

    script += `        ]\n`;
    script += `    }\n\n`;

    script += `    # Execution Logic (Simulation)\n`;
    script += `    print(f"Starting agent: {agent_config['name']}")\n`;
    script += `    # In a real export, this would use the Python SDK to executed the definition\n`;
    script += `    return agent_config\n`;

    return script;
};

export const flowToJson = (nodes: Node[], edges: Edge[], agentName: string) => {
    return JSON.stringify({
        name: agentName,
        nodes,
        edges
    }, null, 2);
};
